from PyQt5 import QtWidgets
from PyQt5.QtCore import QSize, QRect


class GraphPage(QtWidgets.QWidget):
    def __init__(self):
        super(GraphPage, self).__init__()
        self.setEnabled(True)
        self.setObjectName("graph_page")
        self.gridLayout_7 = QtWidgets.QGridLayout(self)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.graph_grid_frame = QtWidgets.QFrame(self)
        self.graph_grid_frame.setObjectName("graph_grid_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.graph_grid_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.vertical_layout_graph_left = QtWidgets.QWidget(self.graph_grid_frame)
        self.vertical_layout_graph_left.setObjectName("vertical_layout_graph_left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.vertical_layout_graph_left)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scatter_plot_radio = QtWidgets.QRadioButton("Scatter Plot", self.vertical_layout_graph_left)
        self.scatter_plot_radio.setObjectName("scatter_plot_radio")
        self.verticalLayout.addWidget(self.scatter_plot_radio)
        self.bar_graph_radio = QtWidgets.QRadioButton("Bar Graph", self.vertical_layout_graph_left)
        self.bar_graph_radio.setObjectName("bar_graph_radio")
        self.verticalLayout.addWidget(self.bar_graph_radio)
        self.histogram_radio = QtWidgets.QRadioButton("Histogram", self.vertical_layout_graph_left)
        self.histogram_radio.setObjectName("histogram_radio")
        self.verticalLayout.addWidget(self.histogram_radio)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_4.addWidget(self.vertical_layout_graph_left, 0, 0, 1, 1)
        self.vertical_layout_graph_right = QtWidgets.QVBoxLayout()
        self.vertical_layout_graph_right.setObjectName("vertical_layout_graph_right")
        self.check_all_horizontal_layout_2 = QtWidgets.QHBoxLayout()
        self.check_all_horizontal_layout_2.setObjectName("check_all_horizontal_layout_2")
        self.Check_all_box_2 = QtWidgets.QCheckBox(self.graph_grid_frame)
        self.Check_all_box_2.setSizeIncrement(QSize(0, 0))
        self.Check_all_box_2.setObjectName("Check_all_box_2")
        self.check_all_horizontal_layout_2.addWidget(self.Check_all_box_2)
        self.searchbar_2 = QtWidgets.QLineEdit(self.graph_grid_frame)
        self.searchbar_2.setObjectName("searchbar_2")
        self.check_all_horizontal_layout_2.addWidget(self.searchbar_2)
        self.vertical_layout_graph_right.addLayout(self.check_all_horizontal_layout_2)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.graph_grid_frame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.vertical_layout_graph_right.addWidget(self.scrollArea_2)
        self.horizontal_layout_generate_button = QtWidgets.QHBoxLayout()
        self.horizontal_layout_generate_button.setObjectName("horizontal_layout_generate_button")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_generate_button.addItem(spacerItem2)
        self.generate_graph = QtWidgets.QPushButton("Generate", self.graph_grid_frame)
        self.generate_graph.setObjectName("generate_graph")
        self.horizontal_layout_generate_button.addWidget(self.generate_graph)

        self.vertical_layout_graph_right.addLayout(self.horizontal_layout_generate_button)
        self.gridLayout_4.addLayout(self.vertical_layout_graph_right, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.graph_grid_frame, 0, 0, 1, 1)
